resolver: lts-8.11

compiler: ghcjs-0.2.1.9008011_ghc-8.0.2

compiler-check: match-exact
extra-deps:
- react-hs-0.0.1
- react-hs-servant-0.0.1
- string-0.4.0

packages:
- location: '.'
- location:
    git: https://github.com/liqula/react-hs
    commit: 3b77a36f3ed869ba37e870f40729017a3e0d5764
  extra-dep: true
  subdirs:
  - react-hs
  - react-hs-servant

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/zerobuzz/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
